version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - delivery-net

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=delivery-connect-configs:1:1,delivery-connect-offsets:1:1
    depends_on:
      - zookeeper
    networks:
      - delivery-net

  connect:
    image: debezium/connect:latest
    container_name: connect
    ports:
      - "8083:8083"
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=delivery-connect-configs
      - OFFSET_STORAGE_TOPIC=delivery-connect-offsets
      - BOOTSTRAP_SERVERS=kafka:9092
      - ADVERTISED_HOST_NAME=connect
    depends_on:
      - zookeeper
      - kafka
      - mysql
    links:
      - zookeeper
      - kafka
      - mysql
    networks:
      - delivery-net

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    restart: always
    networks:
      - delivery-net
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  delivery-net:
    name: delivery-net

volumes:
  mysql-data:

