version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - delivery-net

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      - KAFKA_CREATE_TOPICS=delivery-connect-configs:1:1,delivery-connect-offsets:1:1
    networks:
      - delivery-net

  connect:
    image: debezium/connect:latest
    container_name: connect
    ports:
      - "8083:8083"
    environment:
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=delivery-connect-configs
      - OFFSET_STORAGE_TOPIC=delivery-connect-offsets
      - ADVERTISED_HOST_NAME=connect  # 호스트 IP를 명시적으로 지정
    depends_on:
      - zookeeper
      - kafka
    links:
      - zookeeper
      - kafka
    networks:
      - delivery-net

networks:
  delivery-net:
    name: delivery-net

