spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      data-locations: classpath:import.sql

  jpa:
    defer-datasource-initialization: true
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        storage_engine: innodb
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

springdoc:
  swagger-ui:
    groups-order: DESC
