spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: kafka:9092

  datasource:
    url: jdbc:mysql://localhost:3306/store
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      uri: mongodb://root:1234@localhost:27017
      database: display

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        storage_engine: innodb
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    database: mysql

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    #org.springframework.kafka: debug
